### ISSUE TITLE
Wiki Feedback

### ISSUE THREAD

**Issue by edherm** [PotatoAim11518/GGs-Full-Stack#16]
Hello! 

I am reviewing all group wikis today and wanted to drop this here for y’all to take a look at.

## MVP Feature List
- [x] Remove the empty headers from your 'Nice-to-haves' section.

## Schema
- [x] Your DB Diagram looks like it is linking `reviews` to `usersGames` instead of to the `users` table. Please adjust your Diagram and update that in your wiki.

Once these are taken care of, please drop your responses/updates here as a response to this issue.

Thanks, y'all!!
Ed

**Comment by AnthonyCost** [comment]
Hey there Ed! I am getting started on that right now, we had to restructure our database a little and Alec helped us with that clarity, I will update the Feature List as well as the Schema asap!

**Comment by AnthonyCost** [comment]
The issue is resolved, the wiki is now up to date with our changes as well as the schema reflecting what our new data structure looks like!
